version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: instagram_processor_db
    environment:
      POSTGRES_DB: instagram_processor
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./scripts/test_data.sql:/docker-entrypoint-initdb.d/02_test_data.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d instagram_processor"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  adminer:
    image: adminer:latest
    container_name: instagram_processor_adminer
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    restart: unless-stopped
    environment:
      ADMINER_DEFAULT_SERVER: postgres

volumes:
  postgres_data:
    driver: local